table events1
	lineageTag: b68d3aa6-a60d-4c58-b32f-5c2ca82e3f20

	column event_id
		dataType: string
		lineageTag: dbb7b6a8-c5ae-4936-bd7d-b11c8e64ffc4
		summarizeBy: none
		sourceColumn: event_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: f44859cb-ad6f-4dbc-ae1d-c73ecacb2453
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 8127aaaf-1094-4643-ab07-a21e8c68e3a7
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column event_type
		dataType: string
		lineageTag: ce27fb54-fbae-4d76-8200-15c2213c8fe3
		summarizeBy: none
		sourceColumn: event_type

		annotation SummarizationSetBy = Automatic

	column event_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20b218fa-3630-493b-a700-23f6125e5ee5
		summarizeBy: none
		sourceColumn: event_date

		variation Variation
			isDefault
			relationship: 34553884-c70e-471c-ba51-66b3ae522681
			defaultHierarchy: LocalDateTable_f5b8ca46-20b6-4b09-a6c9-24efd50bede7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition events1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\tanis\OneDrive\All_DataSet\Working_ecommerce_dataset\events1.xlsx"), null, true),
				    events1_Sheet = Source{[Item="events1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(events1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"event_id", type text}, {"user_id", type text}, {"product_id", type text}, {"event_type", type text}, {"event_date", type date}, {"event_time", type datetime}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"event_time"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

