table users1
	lineageTag: 551b3838-0cf9-482a-aa33-278c0bbcd521

	column user_id
		dataType: string
		lineageTag: ccb6f2ec-dd14-4c8f-9340-d16f49d5de20
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column user_name
		dataType: string
		lineageTag: c0410acf-8934-4a0b-82b0-8bb5538daf20
		summarizeBy: none
		sourceColumn: user_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 6f1be0ef-d95b-4d0f-b72f-9074126c5b19
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: e5a7f9da-369a-4f64-9f01-fdcc0c88e93f
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: deee2991-feda-44bb-9db4-8af1b2289104
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column signup_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3eeb19dd-869e-42e5-8f05-c7d15bd850dc
		summarizeBy: none
		sourceColumn: signup_date

		variation Variation
			isDefault
			relationship: 8454919c-5093-4a4e-9960-ffe93c8a0dc5
			defaultHierarchy: LocalDateTable_645020e9-2eba-49ba-ab75-5e5e1d8f1d76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition users1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\tanis\OneDrive\All_DataSet\Working_ecommerce_dataset\users1.xlsx"), null, true),
				    users1_Sheet = Source{[Item="users1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(users1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"user_id", type text}, {"user_name", type text}, {"email", type text}, {"gender", type text}, {"city", type text}, {"signup_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

